### ISSUE TITLE
Azure Spring Cloud-related forums

### ISSUE THREAD

**Issue by bayareagreg** [microsoft/azure-spring-cloud-training#14]
Hello,
sorry for opening a new issue for this, but I don't know another way to get in touch with someone that can answer a technical question on Azure Spring Cloud. MSDN Forum for Azure Spring Cloud appears to be a ghost town https://social.msdn.microsoft.com/Forums/en-US/home?forum=azurespringcloud (grand total of 0 posts as of now) 
1) Is there a forum/slack channel/etc for people asking questions on Azure Spring Cloud
2) Is there a way for me to get in touch with @jdubois directly so I can ask. I do not use Twitter  
Thanks in advance
Greg

**Comment by jdubois** [comment]
Hi @bayareagreg !
I don't think there's a MSDN forum for Azure Spring Cloud, at least I don't know about it, so that's not a very good sign 😀
We do have dedicated channels on MS Teams, @seanli1988 is that publicly available to everybody? Could you invite Greg?
Or Greg you can of course email me: judubois at microsoft.com and I'll do my best to help you.

**Comment by seanli1988** [comment]
Our Teams channel is public. However folks outside of the Microsoft organization needs to be invited into the group. Sign-up link is here<https://aka.ms/AzureSpringCloudInterest>.
Our official support channel for Azure Spring Cloud is via Azure Support Request<https://docs.microsoft.com/azure/azure-supportability/how-to-create-azure-support-request>.

Sean
