### ISSUE TITLE
401Unauthorized when trying to access the properties endpoint

### ISSUE THREAD

**Issue by ravasconcelos** [microsoft/azure-spring-cloud-training#60]
Hi,

If I try to access the properties with a get request like the one below I get 401 Unauthorized. 

`https://<myapp>.svc.azuremicroservices.io/config/application/default`

I am wondering what credentials should I use.

My target is to fetch the logback.xml from the config server. Do you know if is it possible?

https://<myapp>.svc.azuremicroservices.io/config/application/default/master/logback.xml

Thank you in advance.

**Comment by jdubois** [comment]
We are providing a Spring Cloud Config Server, which can serve a Logback configuration as part as the Spring Boot configuration (in your application.yml or application.properties file, you can have a Logback configuration), but this is not made to serve a Logback.xml file.
I guess this might work, because in the end it's only serving files over HTTP, but it's not its normal purpose. On Azure Spring Cloud, this is secured with a certificate - as the Spring Cloud Config client uses it, I'm guessing you can use it too, but again this isn't the way it's supposed to work normally.
Anyway, that's beyond this tutorial, have you asked support for this?

**Comment by ravasconcelos** [comment]
Ok, thanks.
Yes, I have opened a support ticket, let's see what I get.
