### ISSUE TITLE
02 - Build a simple Spring Boot microservice always 404 http error

### ISSUE THREAD

**Issue by huqianghui** [microsoft/azure-spring-cloud-training#9]
I follow https://github.com/microsoft/azure-spring-cloud-training/blob/master/02-build-a-simple-spring-boot-microservice/README.md the deploy, the 404 http error occurs ,when I try to curl test point of the simple-microservice.

It works good  without deploy the jar to the service. How I can to fix it.

**Comment by jdubois** [comment]
You mean that it works on your local machine, but not when you deploy it to Azure Spring Cloud?

It's hard to know without more information, so the best solution is to get some logs: can you follow the next chapter, https://github.com/microsoft/azure-spring-cloud-training/tree/master/03-configure-application-logs , so you configure your application logs? In the training we do that afterwards because this first service is so simple that it shouldn't fail, but for your case it would be better to do the opposite.

Also, there will soon be a new version of the service, where the logs will be much easier to get!!

As soon as you have some logs, can you post them here, so I have a look?

**Comment by jdubois** [comment]
Closing as we chatted about it in parallel
